name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/task-tracker-backend:1.0 
      -     
        name: Deploy Stage
        uses: actions/github-script@v5
        with:
           script: |
            await github.rest.actions.createWorkflowDispatch({
            'immagixe',
            'task-tracker-stack',
            '.github/workflows/deploy.yml',
            'main'
            });
